### ISSUE TITLE
YSFReflector link lost with Ysfgateway.... 

### ISSUE THREAD

**Issue by iw9grl** [g4klx/YSFClients#123] opened 2018-12-23 11:13 UTC
Hi to all

I installed a new YSFReflector on my VPS, all seems to work, it is correctly reachable, I can connect, but after 1 minute in the log appears the message : 

M: 2018-12-23 09:51:54.609 Adding IW9GRL     (73.14.67.668:60637)    <----CONNECTION

M: 2018-12-23 09:52:01.153 Received data from IW9GRL-FT1 to ALL        at IW9GRL   <-- TX

M: 2018-12-23 09:52:02.651 Received end of transmission

M: 2018-12-23 09:52:03.606 Received data from IW9GRL-FT1 to ALL        at IW9GRL   <-- TX

M: 2018-12-23 09:52:06.307 Received end of transmission

M: 2018-12-23 09:52:07.868 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:15.672 Received end of transmission

M: 2018-12-23 09:52:17.089 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:21.790 Received end of transmission

M: 2018-12-23 09:52:23.787 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:32.681 Received end of transmission

M: 2018-12-23 09:52:36.330 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:38.535 Received end of transmission

M: 2018-12-23 09:52:41.722 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:45.125 Received end of transmission

M: 2018-12-23 09:52:53.304 Received data from IW9GRL-FT1 to ALL        at IW9GRL

M: 2018-12-23 09:52:54.615 Removing IW9GRL     (78.15.17.166:60637) disappeared  <-- YSFR disconn.

M: 2018-12-23 09:52:56.102 Network watchdog has expired

M: 2018-12-23 09:53:34.366 No repeaters/gateways linked

after some test, I see  the problem is due to a timeout of YSFGateway that cannot send some info ( I don't know which kind of info ) to the YSFReflector, to link again the YSFR need a restart of YSFGateway, but after 1minute it is unlinked again ........

the problem seems not presenti till the commit : fcf823d837c83119b3c1ca63f979514ad4935be8

thank you
Daniele IW9GRL

**Comment by iw9grl** [comment] 2018-12-25 20:00
Just an update :
the problem is with :  

PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


but with this distribution it works ....

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Pure Debian 8  seems to have problems , Raspbian ( derived from Debian 8 ) works !

I don't understand why ............ same installation , same configuration ....

73

**Comment by iw9grl** [comment] 2019-01-09 19:01
UPDATE :  

Debian 8 - Debian 9 - UBUNTU 18 . same problems .... new VPS in a new Computer Farm ......

**Comment by juribeparada** [comment] 2019-01-28 00:45
I can't reproduce this issue, using latest versions just work fine. Please copy here logs of YSFReflector and YSFGateway with network debug enabled (I want to see YSFP packets), and your *.ini configuration files for both programs. It still looks for me UDP port filtering problem.

**Comment by iw9grl** [comment] 2019-01-28 09:37
Thank you Andy for your kindly answer, I'll send to you later all the informations required .
BR
Daniele ....#

**Comment by iw9grl** [comment] 2019-01-29 18:37
Hi Andy

following the info required : 

[YSFReflector-2019-01-29.log](https://github.com/g4klx/YSFClients/files/2809107/YSFReflector-2019-01-29.log)
[YSFGateway-2019-01-29.log](https://github.com/g4klx/YSFClients/files/2809108/YSFGateway-2019-01-29.log)


[YSFReflector.ini.txt](https://github.com/g4klx/YSFClients/files/2809114/YSFReflector.ini.txt)
[YSFGateway.ini.txt](https://github.com/g4klx/YSFClients/files/2809117/YSFGateway.ini.txt)


The port on remote VPS was opened  : 

hain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     udp  --  anywhere             anywhere             udp dpt:42000

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination 



Thank you for now
73 de IW9GRL

**Comment by juribeparada** [comment] 2019-01-29 20:04
Unfortunately, your YSFReflector log doesn't have any debug information. It should have hex dumps like your YSFGateway log, probably is your log level. Have you tried to use your YSFReflector with daemon=0 and see?

**Comment by iw9grl** [comment] 2019-01-29 22:06
I will try.....

**Comment by iw9grl** [comment] 2019-01-30 07:06
Hi Andy 

with Deamon=1 nothing change in the log : 

M: 2019-01-30 06:59:19.437 Currently linked repeaters/gateways:
M: 2019-01-30 06:59:19.437 Currently linked repeaters/gateways:
M: 2019-01-30 06:59:19.437     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 06:59:19.437     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 07:01:19.448 Currently linked repeaters/gateways:
M: 2019-01-30 07:01:19.448 Currently linked repeaters/gateways:
M: 2019-01-30 07:01:19.448     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 07:01:19.448     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 07:02:54.885 Starting YSFReflector-20161021
M: 2019-01-30 07:02:57.993 Adding BM_YSF_LNK (80.211.95.98:42000)
M: 2019-01-30 07:04:23.175 Adding IW9GRL2    (62.10.124.213:51068)
M: 2019-01-30 07:04:23.175 Adding IW9GRL2    (62.10.124.213:51068)
M: 2019-01-30 07:04:54.895 Currently linked repeaters/gateways:
M: 2019-01-30 07:04:54.895 Currently linked repeaters/gateways:
M: 2019-01-30 07:04:54.895     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 07:04:54.895     BM_YSF_LNK: 80.211.95.98:42000 1/60
M: 2019-01-30 07:04:54.895     IW9GRL2   : 62.10.124.213:51068 31/60
M: 2019-01-30 07:04:54.895     IW9GRL2   : 62.10.124.213:51068 31/60
M: 2019-01-30 07:05:23.181 Removing IW9GRL2    (80.211.95.98:42000) disappeared
M: 2019-01-30 07:05:23.181 Removing IW9GRL2    (80.211.95.98:42000) disappeared

**Comment by juribeparada** [comment] 2019-02-01 10:49
After long time waiting for you, now it should be fixed in the current YSFGateway master branch. Thank you for sharing the information and the access to the server, otherwise I wouldn't find this problem correctly.

**Comment by iw9grl** [comment] 2019-02-01 12:59
I want to confirm that the issue is fixed. thank you Andy for you big effort and support.....

**Closed** 2019-02-01 12:59 UTC

**Comment by g4klx** [comment] 2019-02-01 13:07
Does the same bug exist in P25 and/or NXDN? They were based on YSF originally.


Sent from Yahoo Mail for iPhone


On Friday, February 1, 2019, 10:49, Andy CA6JAU <notifications@github.com> wrote:


After long time waiting for you, now it should be fixed in the current YSFGateway master branch. Thank you for sharing the information and the access to the server, otherwise I wouldn't find this problem correctly.

**Comment by juribeparada** [comment] 2019-02-01 13:19
No, P25 and NXDN gateways use the poll timer in the main class, they are correct. Only YSFGateway was affected.
