### ISSUE TITLE
When starting the YSF reflector  it gets stuck

### ISSUE THREAD

**Issue by kc9gqr** [g4klx/YSFClients#76] opened 2016-10-10 12:33 UTC
Hello,  

I just installed a new image   of jessie  and  installed YSF clients.. Now when I start YSF Reflector i get  to the following point and it sticks..  all i get on the terminal screen is  Opening YSF Network connection and that is as far as it goes..    doesn't appear to do anything else..  

Bradley
kc9gqr

**Comment by dg9vh** [comment] 2017-09-17 07:32
is this a doublet of https://github.com/g4klx/YSFClients/issues/84 ?

**Comment by ChrisK9EQ** [comment] 2018-11-27 16:40
Insufficient information to address this issue. The issue is OLD. Suggest closing without action.

**Closed** 2018-11-27 17:31 UTC
