### ISSUE TITLE
Please assign a YSF room number for XLXCAT

### ISSUE THREAD

**Issue by yo3cat** [g4klx/YSFClients#241] opened 2021-01-12 07:11 UTC
Good morning,

Please assign a YSF room number for XLXCAT (xlxcat.dstar-yo.ro)

Thank you,
Catalin 
YO3CAT

**Comment by g4klx** [comment] 2021-01-16 12:35
Just create your reflector and it will assign itself an id. It is automatic.

**Comment by dg9vh** [comment] 2021-01-27 22:41
@yo3cat did you already register your reflector at https://register.ysfreflector.de/ ? Seems not.

73 de Kim
DG9VH

**Comment by dg9vh** [comment] 2021-02-27 22:21
Seems the issue is not persistent anymore because of no reaction - @g4klx I think you can close it :-)

**Closed** 2021-02-28 13:26 UTC
